services:
  - type: web
    name: voltage
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VOLTAGE_NAME
        value: Voltage
